name: Build

on:
  push:
  pull_request:
    branches:
      - develop
      - main

jobs:
  emscripten:
    name: Emscripten
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4
        with:
          submodules: 'recursive'

      - name: Set up Python (required for Emscripten)
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install Emscripten SDK
        run: |
          git clone https://github.com/emscripten-core/emsdk.git
          cd emsdk
          ./emsdk install latest
          ./emsdk activate latest
          source ./emsdk_env.sh
        shell: bash

      - name: Build
        run: |
          source emsdk/emsdk_env.sh
          emcmake cmake . -B build -DCMAKE_BUILD_TYPE=Release
          cmake --build build --config=Release
        shell: bash
      
      - name: Clean Up Pre-Artifact
        run: |
          cd build
          rm -rf CMakeFiles raylib cmake_install.cmake CMakeCache.txt CPackConfig.cmake CPackSourceConfig.cmake Makefile
      
      - name: Upload Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: 4MB_Game_Jam_2025.Web
          path: build/*

  ubuntu:
    name: Ubuntu
    runs-on: ubuntu-24.04
  
    steps:
      - name: Checkout source code
        uses: actions/checkout@v4
        with:
          submodules: 'recursive'

      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y zlib1g-dev libpng-dev libx11-dev libgl1-mesa-dev libglu1-mesa-dev

      - name: Set default gcc and g++ versions to latest
        run: |
          sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-13 100
          sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-13 100
            
      - name: Build
        env:
          CC: gcc
          CXX: g++
        run: |
          cmake . -B build -DCMAKE_BUILD_TYPE=Release
          cmake --build build --config=Release
        shell: bash
      
      - name: Clean Up Pre-Artifact
        run: |
          cd build
          rm -rf CMakeFiles raylib cmake_install.cmake CMakeCache.txt CPackConfig.cmake CPackSourceConfig.cmake Makefile

      - name: Upload Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: 4MB_Game_Jam_2025.Ubuntu
          path: build/*

  windows:
    name: Windows
    runs-on: windows-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v4
        with:
          submodules: 'recursive'
      
      - name: Build
        run: |
          cmake -S . -B build -DCMAKE_BUILD_TYPE=Release
          cmake --build build --config=Release
        shell: pwsh

      - name: Upload Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: 4MB_Game_Jam_2025.Windows
          path: build/Release/*
  release:
    name: Release
    needs: [emscripten, ubuntu, windows]  
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout source code
        uses: actions/checkout@v4
      
      - name: Download Emscripten Artifact
        uses: actions/download-artifact@v4
        with:
          name: 4MB_Game_Jam_2025.Web
          path: artifacts/4MB_Game_Jam_2025.Web

      - name: Download Ubuntu Artifact
        uses: actions/download-artifact@v4
        with:
          name: 4MB_Game_Jam_2025.Ubuntu
          path: artifacts/4MB_Game_Jam_2025.Ubuntu

      - name: Download Windows Artifact
        uses: actions/download-artifact@v4
        with:
          name: 4MB_Game_Jam_2025.Windows
          path: artifacts/4MB_Game_Jam_2025.Windows
      
      - name: Zip Artifacts
        run: |
          (cd artifacts/4MB_Game_Jam_2025.Web; zip -r ../4MB_Game_Jam_2025.Web.zip .)
          (cd artifacts/4MB_Game_Jam_2025.Ubuntu; zip -r ../4MB_Game_Jam_2025.Ubuntu.zip .)
          (cd artifacts/4MB_Game_Jam_2025.Windows; zip -r ../4MB_Game_Jam_2025.Windows.zip .)
      
      - name: Confirm Files
        id: list-files
        run: ls -Al artifacts

      - name: Get commit SHA
        id: commit
        run: echo "COMMIT_SHA=${{ github.sha }}" >> $GITHUB_ENV
      
      - name: Delete existing latest release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release delete latest --yes || true
        continue-on-error: true

      - name: Create or Update Latest Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release create latest \
            --title "Latest Release" \
            --notes "Latest release with artifacts from commit ${{ env.COMMIT_SHA }}." \
            --draft=false \
            --prerelease=false \
            --target ${{ github.sha }} \
            artifacts/4MB_Game_Jam_2025.Web.zip \
            artifacts/4MB_Game_Jam_2025.Windows.zip